name: build

on: workflow_dispatch

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt-hotspot
        java-version: 17
        cache: gradle
    - name: Build Normal Flavor
      run: bash ./gradlew assembleEmbedNoRecordRelease
    - name: Build Release-specific Binaries
    - name: Artifact (Normal unsigned APK)
      if: ${{ matrix.build_type == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: love-android.apk
        path: app/build/outputs/apk/**/*.apk
    - name: Artifact (Debug symbols)
      uses: actions/upload-artifact@v4
      with:
        name: love-android-unstripped-debugsyms-${{ matrix.build_type }}
        path: love/build/intermediates/library_jni
